"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2. the first 10 terms will be:
3
int main() {
19
sum += b;
20
}
1, 2, 3, 5, 8, 13, 21, 34, 55, 89,..
21
22
long long next_term= a + b;
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
23
a = b;
b = next_term;
24
25
Submissions
Input Format
26
27
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer. N.
28
}
29
printf("%lld\n", sum);
30
Constraints
31
}
32
33
1<T<105
return 0;
34
"""
#The code
include <stdio.h>

int main() {
    int t;
    
    scanf("%d", &t);

    // Loop through each test case
    while (t--) {
        long long n;
        
        scanf("%lld", &n);
        
        long long a = 0;
        long long b = 1;
        long long sum = 0;
                while (b <= n) {
            if (b % 2 == 0) {
                sum += b;
            }
            long long next_term = a + b;
            a = b;
            b = next_term;
 
        
        
        
    }
            printf("%lld\n", sum);

    }
    
    return 0;
}
10 ≤ N ≤ 4 x 1016
